name: 🐍 Contribution Snake

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: manuel15963
          github_token: ${{ secrets.PROFILE_TOKEN }}
          outputs: |
            assets/github-snake.svg?color_snake=%237C3AED&color_dots=%23EDE9FE,%23C4B5FD,%23A78BFA,%238B5CF6,%236D28D9
            assets/github-snake-dark.svg?palette=github-dark&color_snake=%23A855F7&color_dots=%23161B22,%231E3A8A,%233B82F6,%237C3AED,%23A855F7

      - name: Save snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/
          git commit -m "chore: update contribution snake" || exit 0
          git pull --rebase --autostash
          git push
